# .github/workflows/pipeline.yml
name: Github Actions Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      - name: Run smoke tests
        run: mvn clean test -Dgroups=smoke

      - name: Run regression tests
        run: mvn clean test -Dgroups=regression